#!/usr/bin/perl
use esmith::Build::CreateLinks qw(:all);

for my $event (qw (user-modify user-create)) {
event_actions($event, 'nethserver-password-policies-update' => '99');
}

my $event = "nethserver-password-update";
event_actions($event, 
'initialize-default-databases' => '00',
'nethserver-password-PassExpires2yes-conf' => '10');
