#!/usr/bin/perl -w
# used to add the property PassExpires to yes if it doesn't already exist
# for users created before the installation of nethserver-password

use esmith::AccountsDB;
use esmith::DB;
my $a = esmith::AccountsDB->open;
my @users    = $a->users();
foreach $users (@users) {
    my $PassExpires = $users->prop('PassExpires');
    next unless ( ! $PassExpires );
    $users->merge_props(PassExpires => 'yes');
    }
