#!/usr/bin/perl -w

## Used to add the property PassExpires to yes if it doesn't already exist
## for users created before the installation of nethserver-password
## Called before the action S40nethserver-directory-password-policy
## for event user-modify and user-create if users are created
## by /usr/share/doc/nethserver-directory-<ver>/import_users

use esmith::AccountsDB;
use esmith::DB;

my $event = shift;
my $userName = shift;
my $a = esmith::AccountsDB->open;
my @users;

if ($userName) {
@users = $a->get($userName);
} else {
@users = $a->users();
}

foreach $users (@users) {
    my $PassExpires = $users->prop('PassExpires');
    next unless ( ! $PassExpires );
    $users->merge_props(PassExpires => 'yes');
    }
